DROP SCHEMA IF EXISTS kyc CASCADE;

CREATE SCHEMA kyc;
SET search_path TO kyc;

DROP TABLE IF EXISTS kyc.person CASCADE;

CREATE TABLE person
(
    id VARCHAR NOT NULL,
    schema VARCHAR,
    name VARCHAR NOT NULL,
   	aliases VARCHAR,
    birth_date VARCHAR,
    countries VARCHAR,
    addresses VARCHAR,
    identifiers VARCHAR,
    sanctions VARCHAR,
    phones VARCHAR,
    emails VARCHAR,
    dataset VARCHAR,
	last_seen TIMESTAMP,
	first_seen TIMESTAMP,
	PRIMARY KEY (id)

);

